name: explorehubplugin
version: '${project.version}'
main: org.explorehubplugin.explorehubplugin.Explorehubplugin
api-version: 1.19
commands:
  setteleportlocation:
    description: Creates a teleport Location at your current position.
    usage: /setteleportlocation [Name] A single word [Description] A String of words [Block] A valid Minecraft block
permissions:
  explorehub.admin:
    description: "admin"
    default: op
  explorehub.user:
    description: "user"
    default: not op